// frontend/src/views/New.vue
<template>
  <form @submit.prevent="handleSubmit">
    <!-- service, username, password, master_password -->
    <h1>New credential</h1>
    <div>
      <label for="service">Service</label>
      <input type="text" id="service" v-model="service" required>
    </div>
    <div>
      <label for="username">Username</label>
      <input type="text" id="username" v-model="username" required>
    </div>
    <div>
      <label for="password">Password</label>
      <input type="password" id="password" v-model="password" required>
    </div>
    <div>
      <label for="master_password">Master Password</label>
      <input type="password" id="master_password" v-model="master_password" required>
    </div>
    <button type="submit">Save</button>
  </form>
</template>

<script setup>
import { ref } from 'vue';
import { useRouter } from 'vue-router';

const router = useRouter();
const service = ref('');
const username = ref('');
const password = ref('');
const master_password = ref('');

const handleSubmit = async () => {
  try {
    const token = localStorage.getItem('api_token');
    const response = await fetch('/api/v1/credentials', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        service: service.value,
        username: username.value,
        password: password.value,
        master_password: master_password.value,
      }),
    });

    if (!response.ok) {
      throw new Error('Network response was not ok');
    }

    alert('Credential saved successfully!');
    router.push('/');
  } catch (error) {
    console.error('Failed to save credential:', error);
    alert('Failed to save credential. Please try again.');
  }
};
</script>

<style scoped>
form {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  /* max-width: 300px; */
  margin: 8px;
  padding: 1rem;
  border: 1px solid #ccc;
  border-radius: 4px;
}

form div {
  display: flex;
  flex-direction: column;
}

@media screen and (max-width: 440px) {
  form {
    border: none;
  }
}
</style>

// frontend/src/routes/new/+page.svelte
<form on:submit|preventDefault={addCredential} class="mx-auto max-w-md">
  <h2>Add New Credential</h2>
  <label>
    Service:
    <input type="text" bind:value={newCredential.service} required />
  </label>
  <label>
    Username:
    <input type="text" bind:value={newCredential.username} required />
  </label>
  <label>
    Password:
    <input type="password" bind:value={newCredential.password} required />
  </label>
  <label>
    Master Password:
    <input type="password" bind:value={newCredential.master_password} required />
  </label>
  <button type="submit">Add Credential</button>
</form>

{#if responseMessage}
<div class="mt-4 whitespace-pre-wrap">
  <h3>Response:</h3>
  <pre>{responseMessage}</pre>
</div>
{/if}

<script lang="ts">
  let newCredential = {
    master_password: '',
    service: '',
    username: '',
    password: ''
  };
  let responseMessage = '';

  async function addCredential() {
    const apiToken = localStorage.getItem('apiToken');
    if (apiToken) {
      try {
        const response = await fetch('http://localhost:8000/api/v1/credentials', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${apiToken}`
          },
          body: JSON.stringify(newCredential)
        });
        responseMessage = response.ok ? 'Credential added successfully!' : 'Failed to add credential';
        if (response.ok) {

          // const addedCredential = await response.json();
          // if (!credentials[addedCredential.service]) {
          //   credentials[addedCredential.service] = [];
          // }
          // credentials[addedCredential.service].push(addedCredential);
          // newCredential = { service: '', username: '', password: '' };
        } else {
          console.error('Failed to add credential');
        }
      } catch (error) {
        console.error('Error:', error);
      }
    }
  }
</script>

<style>
  form {
    margin-top: 2em;
  }

  label {
    display: block;
    margin: 0.5em 0;
  }

  input {
    width: 100%;
    padding: 0.5em;
    margin-top: 0.2em;
    border: 1px solid #ccc;
    border-radius: 5px;
  }

  button {
    display: inline-block;
    margin-top: 1em;
    padding: 0.5em 1em;
    color: white;
    background-color: #3498db;
    text-decoration: none;
    border: none;
    border-radius: 5px;
    cursor: pointer;
  }

  button:hover {
    background-color: #2980b9;
  }
</style>
